from __future__ import annotations

from dataclasses import dataclass
import numpy as np

from .advanced import CoupledWeatherModel, ExtendedWeatherState


FEATURE_NAMES = [
    "mean_h", "std_h", "mean_u", "mean_v", "mean_temp", "mean_q", "mean_rain", "max_wind"
]


def features(s: ExtendedWeatherState) -> np.ndarray:
    wind = np.sqrt(s.u*s.u + s.v*s.v)
    return np.array([
        np.mean(s.h), np.std(s.h), np.mean(s.u), np.mean(s.v),
        np.mean(s.temperature_k), np.mean(s.specific_humidity),
        np.mean(s.rain_rate), np.max(wind),
    ], dtype=float)


@dataclass
class DiagnosticEmulator:
    """Small ridge-regression surrogate for one-step diagnostic evolution.

    It learns the mapping from current summary diagnostics to the next summary
    diagnostics generated by the physical model. It does not replace a
    gridded numerical weather model; it demonstrates a learned emulator layer.
    """

    weights: np.ndarray
    feature_mean: np.ndarray
    feature_scale: np.ndarray

    def predict(self, x: np.ndarray) -> np.ndarray:
        z = (x - self.feature_mean) / self.feature_scale
        design = np.concatenate([[1.0], z])
        return design @ self.weights


def train_emulator(
    model: CoupledWeatherModel,
    initial: ExtendedWeatherState,
    samples: int = 48,
    ridge: float = 1e-3,
) -> tuple[DiagnosticEmulator, dict[str, float]]:
    states = [initial.copy()]
    s = initial.copy()
    for _ in range(samples):
        s = model.step(s)
        states.append(s)

    x = np.stack([features(s) for s in states[:-1]])
    y = np.stack([features(s) for s in states[1:]])
    mu = x.mean(axis=0)
    scale = x.std(axis=0)
    scale[scale < 1e-9] = 1.0
    z = (x - mu) / scale
    X = np.column_stack([np.ones(len(z)), z])
    reg = ridge * np.eye(X.shape[1])
    reg[0, 0] = 0.0
    w = np.linalg.solve(X.T @ X + reg, X.T @ y)
    emulator = DiagnosticEmulator(w, mu, scale)
    pred = X @ w
    rmse = np.sqrt(np.mean((pred - y)**2, axis=0))
    metrics = {f"{name}_one_step_rmse": float(value) for name, value in zip(FEATURE_NAMES, rmse)}
    return emulator, metrics
